# Generated by Django 4.0 on 2022-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnicare', '0002_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
