# Generated by Django 4.0 on 2022-01-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnicare', '0003_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='manu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='qty',
            field=models.IntegerField(default=''),
        ),
    ]
