# Generated by Django 4.0 on 2022-01-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnicare', '0004_alter_medicine_manu_alter_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='manu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
