# Generated by Django 4.0 on 2022-01-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omnicare', '0007_alter_medicine_price_alter_medicine_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='omnicare.doctor'),
        ),
    ]
