# Generated by Django 4.0 on 2022-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnicare', '0010_bill_patient_id_supplier_nurse_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='patien_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
