# Generated by Django 4.0 on 2022-01-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnicare', '0011_remove_bill_patient_id_bill_patien_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='descr',
            field=models.TextField(null=True),
        ),
    ]
