# Generated by Django 4.0 on 2022-01-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnicare', '0012_supplier_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='quo_price',
            field=models.IntegerField(null=True),
        ),
    ]
